<a href="https://colab.research.google.com/github/douniaedben/Data-Analysis/blob/main/datacleaninglab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
import os

In [ ]:

dirty_data = pd.read_csv('/content/drive/MyDrive/dirty_ecommerce_transactions.csv', encoding='latin1')
dirty_data.head(10)

,Transaction_ID,Customer_Name,Customer_Email,Transaction_Amount,Product_Category,Transaction_Date
0,45b2a99c-0210-43fe-bbb0-edfef4e5f740,Matthew Rios,tyronenewman@hanson.com,288.34,fashion,18/06/2023
1,c43b2683-9b0c-44f2-af4d-5ddee4d02dd4,Yolanda Robinson,holtshelley@gmail.com,362.52,Health & Beauty,13/12/2023
2,268952d6-1eff-4d1c-8751-bfa16ba5297d,Latoya Chambers,ddaniels@colon.com,903.14,home,13/06/2023
3,89a12304-aa99-4e0e-86d7-09553d606567,Michael Rodriguez,tglass@stanley.org,270.0,health,15/05/2022
4,e0858e59-4bf9-4f4d-bcdd-682917fefca4,Barbara Lewis,robertbennett@crosby-thompson.info,3.72,electronics,21/02/2023
5,0172f04e-e238-48dd-ba42-f4c0db2ed019,Rebecca Jennings,pchristensen@gmail.com,242.75,Health & Beauty,10/12/2021
6,ed5a0b7c-2f29-4b54-9f04-8cf94260aae8,Frank Buckley,nancy73@garrison.com,NaN,health,01/02/2022
7,bd6dd22b-bb65-4634-8823-a2073a4d7040,Amy Vega,nathanielbailey@henderson.info,14.27,beauty,31/07/2022
8,a36b1f26-3a4c-4c50-96f0-ee880de7a00e,Ryan Benson,duartekristin@anderson.biz,356.17,Health & Beauty,14/04/2024
9,1726909d-808d-469a-a3a4-348a5a5b5fe0,Jay Rodriguez,nballard@douglas-singh.com,636.69,Electronics,08/05/2024

In [ ]:
dirty_data.sample(5)

,Transaction_ID,Customer_Name,Customer_Email,Transaction_Amount,Product_Category,Transaction_Date
3431,1c1fbdfb-c4d3-46dd-8f02-6b286c3bd16e,Robert Harrington,andrewswilliam@conley.biz,536.61,fashion,03/04/2024
8819,e2a2202d-4286-485e-a5e5-ebe88b749092,Daniel Bryan,hamptonjeffrey@graham.info,529.4,home,05/08/2022
5394,5ed0339e-d668-434c-b9e8-0ce8727f06d2,Bradley Chandler,jessica13@holland.info,92.09,beauty,12/02/2023
8692,d8b2e31a-8868-4a93-bf55-4fe493b26790,Shannon Morton,malonedanielle@yahoo.com,959.84,Electronics,12/05/2024
3619,11274180-bb5a-453d-b263-c37e234793d6,Jason Cain,allenjohn@gmail.com,30.72,Electronics,24/01/2023

In [ ]:
dirty_data.info()
rows, columns = dirty_data.shape
print(f'The dataset has {rows} rows and {columns} columns')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10200 entries, 0 to 10199
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Transaction_ID      10200 non-null  object
 1   Customer_Name       10197 non-null  object
 2   Customer_Email      9685 non-null   object
 3   Transaction_Amount  10095 non-null  object
 4   Product_Category    10197 non-null  object
 5   Transaction_Date    10197 non-null  object
dtypes: object(6)
memory usage: 478.2+ KB
The dataset has 10200 rows and 6 columns

In [ ]:
dirty_data.describe()

,Transaction_ID,Customer_Name,Customer_Email,Transaction_Amount,Product_Category,Transaction_Date
count,10200,10197,9685,10095,10197,10197
unique,10004,9300,9451,9450,9,1106
top,f2670b44-f1aa-421d-888e-26489fe3b356,Michael Smith,lsmith@hotmail.com,233.85,home,05/01/2024
freq,2,10,4,4,1490,21

In [ ]:
dirty_data['Transaction_ID'].isnull().sum()

0

In [ ]:
dirty_data['Transaction_ID'].duplicated().sum()

196

In [ ]:
missing_values= dirty_data.isnull().sum()
missing_values

Transaction_ID          0
Customer_Name           3
Customer_Email        515
Transaction_Amount    105
Product_Category        3
Transaction_Date        3
dtype: int64

In [ ]:

missing_columns = missing_values[missing_values > 0]
print("Columns with Missing Values:")
print(missing_columns)

Columns with Missing Values:
Customer_Name           3
Customer_Email        515
Transaction_Amount    105
Product_Category        3
Transaction_Date        3
dtype: int64

In [ ]:

dirty_data['Customer_Name'].fillna('Unknown', inplace=True)

# Drop rows
dirty_data = dirty_data.dropna(subset=['Customer_Email'])

dirty_data['Transaction_Amount'] = pd.to_numeric(dirty_data['Transaction_Amount'], errors='coerce')  # Convert to numeric
median_amount = dirty_data['Transaction_Amount'].median()
dirty_data['Transaction_Amount'].fillna(median_amount, inplace=True)

# Drop rows
dirty_data = dirty_data.dropna(subset=['Product_Category', 'Transaction_Date'])
dirty_data.info()
dirty_data.sample(10)

<class 'pandas.core.frame.DataFrame'>
Index: 9685 entries, 0 to 10199
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Transaction_ID      9685 non-null   object
 1   Customer_Name       9685 non-null   object
 2   Customer_Email      9685 non-null   object
 3   Transaction_Amount  9685 non-null   float64
 4   Product_Category    9685 non-null   object
 5   Transaction_Date    9685 non-null   object
dtypes: float64(1), object(5)
memory usage: 529.6+ KB

<ipython-input-5-6f4ea18e1c3f>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dirty_data['Customer_Name'].fillna('Unknown', inplace=True)
<ipython-input-5-6f4ea18e1c3f>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dirty_data['Transaction_Amount'] = pd.to_numeric(dirty_data['Transaction_Amount'], errors='coerce')  # Convert to numeric
<ipython-input-5-6f4ea18e1c3f>:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dirty_data['Transaction_Amount'].fillna(median_amount, inplace=True)
<ipython-input-5-6f4ea18e1c3f>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dirty_data['Transaction_Amount'].fillna(median_amount, inplace=True)

,Transaction_ID,Customer_Name,Customer_Email,Transaction_Amount,Product_Category,Transaction_Date
9868,71883c86-f069-4f92-85c3-3b1f19f7f918,Kelsey Valencia,dchambers@mcgee.com,993.60,Electronics,26/07/2023
2297,db3f17d8-52b5-4dd4-b281-7437aa2c9059,Anna Stanley,diane29@yahoo.com,23.29,Health & Beauty,03/07/2022
6191,65618bd3-968d-4328-9773-dca7978ecca9,Jeremy Smith,hsingleton@perry.com,494.88,beauty,13/09/2023
1459,464fc8f1-a53e-4ba5-9ddc-efc3693fb4a2,Andrea Lopez,vickiedelgado@newman.org,7.90,Electronics,02/10/2024
6234,71f7a65d-c8f1-45b1-b096-cb61bc1960f9,Chloe Walls,jacqueline64@fernandez-livingston.com,914.58,electronics,05/01/2024
190,5ac13cf5-609c-40de-b4fc-e2db2788bc4f,Blake Brown,andersoncaitlin@yahoo.com,202.91,beauty,10/06/2022
9187,17ff597b-b28a-406b-807a-8685ccbe05ff,Jesse Medina,harrisblake@hotmail.com,658.13,Electronics,16/04/2023
50,fe03d297-fe52-4871-9bee-b277ee2e7cf6,Timothy Williams,hernandezbenjamin@yahoo.com,567.76,fashion,04/10/2023
8926,67dc4e8a-eaa2-4e0f-b299-9c26735e62d3,Tony Pratt,williedavis@potter-buck.info,426.86,beauty,25/07/2023
8721,079ade12-48a8-45b0-ad4b-3a0ea2c5c437,Jennifer Washington,davidcole@gmail.com,476.64,Health & Beauty,22/05/2022

In [ ]:
# date to standard date format
dirty_data['Transaction_Date'] = pd.to_datetime(dirty_data['Transaction_Date'], errors='coerce')
date_columns = dirty_data.select_dtypes(include=['datetime']).columns
print("Date Columns:")
print(date_columns)

#  Product_Category to lowercase
dirty_data['Product_Category'] = dirty_data['Product_Category'].str.lower()

# Check for non-numeric values in 'Transaction_Amount' and handle them
dirty_data['Transaction_Amount'] = pd.to_numeric(dirty_data['Transaction_Amount'], errors='coerce')

dirty_data.sample(5)

Date Columns:
Index(['Transaction_Date'], dtype='object')

,Transaction_ID,Customer_Name,Customer_Email,Transaction_Amount,Product_Category,Transaction_Date
6125,2d3648e7-d294-4e4d-85cb-da81964e3193,Gabrielle White,sbrown@yahoo.com,552.76,beauty,2024-09-14
3260,fedd17d3-58d1-4d48-89f6-7bddd9a5a13b,Brandon Chaney,cervantesjohn@schultz.net,4.37,health & beauty,2022-07-29
3806,84c354c3-f67c-49f0-b6cf-59aa351833f7,Gary Davis,qthomas@day.com,377.35,fashion,2022-11-09
667,d4a3e504-2a7a-4b47-9f72-6e2110918870,Mary Henry,kimberlybrown@yahoo.com,-1.55,health,2022-01-27
369,e220d75e-9760-48bf-9402-0e3a5dcc9e16,Rhonda Davis,nicholaskennedy@hotmail.com,975.08,beauty,2022-09-14

In [ ]:
# Identify all columns with text data object type columns
text_columns = dirty_data.select_dtypes(include=['object']).columns

#  Capitalizing first letters
for col in text_columns:
    dirty_data[col] = dirty_data[col].str.title()

# Check the updated dataset
print(dirty_data.head())

                         Transaction_ID      Customer_Name  \
0  45B2A99C-0210-43Fe-Bbb0-Edfef4E5F740       Matthew Rios
1  C43B2683-9B0C-44F2-Af4D-5Ddee4D02Dd4   Yolanda Robinson
2  268952D6-1Eff-4D1C-8751-Bfa16Ba5297D    Latoya Chambers
3  89A12304-Aa99-4E0E-86D7-09553D606567  Michael Rodriguez
4  E0858E59-4Bf9-4F4D-Bcdd-682917Fefca4      Barbara Lewis

                       Customer_Email  Transaction_Amount Product_Category  \
0             Tyronenewman@Hanson.Com              288.34          Fashion
1               Holtshelley@Gmail.Com              362.52  Health & Beauty
2                  Ddaniels@Colon.Com              903.14             Home
3                  Tglass@Stanley.Org              270.00           Health
4  Robertbennett@Crosby-Thompson.Info                3.72      Electronics

  Transaction_Date
0       2023-06-18
1       2023-12-13
2       2023-06-13
3       2022-05-15
4       2023-02-21

In [ ]:



# Detect and cap outliers in 'Transaction_Amount' using IQR ....> cour
Q1 = dirty_data['Transaction_Amount'].quantile(0.25)
Q3 = dirty_data['Transaction_Amount'].quantile(0.75)
IQR = Q3 - Q1
lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

# Cap values outside the range
dirty_data['Transaction_Amount'] = dirty_data['Transaction_Amount'].clip(lower=lower_limit, upper=upper_limit)

dirty_data.sample(5)

,Transaction_ID,Customer_Name,Customer_Email,Transaction_Amount,Product_Category,Transaction_Date
4066,9c563852-219c-414a-b998-08a20c97892b,Justin Young,scotttony@smith-stephens.net,717.31,beauty,2024-06-15
791,5061f1f8-e86e-417c-8637-5bf28647ae3e,Cody Neal,austinjason@yahoo.com,873.57,fashion,2024-10-16
7812,22d1e095-10b3-4368-a03a-ecc886a9f236,Robert Stevens,fordjoseph@yahoo.com,845.01,fashion,2023-09-09
659,d26f1edf-61d0-426c-a0a8-27bc15cdd234,Angela Frank,clarkheidi@yahoo.com,371.75,electronics,2024-02-05
9437,4ad6abf3-3392-494a-921e-ef5e1a5e8eeb,Brian Jenkins,opitts@gmail.com,40.04,electronics,2024-06-10

from matplotlib import pyplot as plt
_df_17['Transaction_Amount'].plot(kind='hist', bins=20, title='Transaction_Amount')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_18.groupby('Transaction_ID').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_19.groupby('Customer_Name').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_20.groupby('Customer_Email').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_21.groupby('Product_Category').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Transaction_Date']
  ys = series['Transaction_Amount']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_22.sort_values('Transaction_Date', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Transaction_ID')):
  _plot_series(series, series_name, i)
  fig.legend(title='Transaction_ID', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Transaction_Date')
_ = plt.ylabel('Transaction_Amount')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Transaction_Date']
  ys = series['Transaction_Amount']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_23.sort_values('Transaction_Date', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Customer_Name')):
  _plot_series(series, series_name, i)
  fig.legend(title='Customer_Name', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Transaction_Date')
_ = plt.ylabel('Transaction_Amount')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Transaction_Date']
  ys = series['Transaction_Amount']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_24.sort_values('Transaction_Date', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Customer_Email')):
  _plot_series(series, series_name, i)
  fig.legend(title='Customer_Email', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Transaction_Date')
_ = plt.ylabel('Transaction_Amount')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Transaction_Date']
  ys = series['Transaction_Amount']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_25.sort_values('Transaction_Date', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Product_Category')):
  _plot_series(series, series_name, i)
  fig.legend(title='Product_Category', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Transaction_Date')
_ = plt.ylabel('Transaction_Amount')

from matplotlib import pyplot as plt
_df_26['Transaction_Amount'].plot(kind='line', figsize=(8, 4), title='Transaction_Amount')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Customer_Name'].value_counts()
    for x_label, grp in _df_27.groupby('Transaction_ID')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Transaction_ID')
_ = plt.ylabel('Customer_Name')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Customer_Email'].value_counts()
    for x_label, grp in _df_28.groupby('Customer_Name')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Customer_Name')
_ = plt.ylabel('Customer_Email')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Product_Category'].value_counts()
    for x_label, grp in _df_29.groupby('Customer_Email')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Customer_Email')
_ = plt.ylabel('Product_Category')

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_30['Transaction_ID'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_30, x='Transaction_Amount', y='Transaction_ID', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_31['Customer_Name'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_31, x='Transaction_Amount', y='Customer_Name', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_32['Customer_Email'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_32, x='Transaction_Amount', y='Customer_Email', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_33['Product_Category'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_33, x='Transaction_Amount', y='Product_Category', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
# Remove duplicate rows
dirty_data = dirty_data.drop_duplicates()

# Check duplicates removal
print(f"Dataset Shape after removing duplicates: {dirty_data.shape}")

Dataset Shape after removing duplicates: (9504, 6)

In [ ]:
dirty_data.duplicated().sum()

0

In [ ]:
# Standardize 'Product_Category' values and fix common typos
category_corrections = {
    'elecronics': 'electronics',
    'fashiion': 'fashion',
    'hoome': 'home',
     'health': 'health & beauty',
    'beauty': 'health & beauty'
}

dirty_data['Product_Category'] = dirty_data['Product_Category'].replace(category_corrections)
dirty_data['Product_Category'] = dirty_data['Product_Category'].str.lower()

print(dirty_data['Product_Category'].unique())

['fashion' 'health & beauty' 'home' 'electronics']

In [ ]:
# Display final dataset shape and save to a new file
print(f"Final Dataset Shape: {dirty_data.shape}")
dirty_data.to_csv('/content/drive/MyDrive/cleaned_ecommerce_transactions.csv', index=False)

dirty_data.sample(5)

Final Dataset Shape: (9503, 6)

,Transaction_ID,Customer_Name,Customer_Email,Transaction_Amount,Product_Category,Transaction_Date
7661,F37C4Ff0-66A4-445E-Bebb-F7983347441B,Ashley Miller,Millerjessica@Hotmail.Com,881.54,electronics,2023-11-25
4656,2975E0D1-996E-43D0-B86B-A9279A2Bcfab,Brianna Valencia,Unorton@Johnson.Com,830.31,home,2024-07-09
6558,A913D954-5E0C-4D00-8296-F8D57E685196,Tara Hill,Jeremygarza@Gmail.Com,0.85,health & beauty,2024-02-16
1916,4308Cae4-E106-43A8-B99E-09378D61C7F6,Morgan Schwartz,Aortega@Hotmail.Com,213.59,electronics,2024-04-25
8871,Ee97D4Df-9Cb8-4184-8Ac8-8F3481D9F2De,Lauren Meadows,Coltonmartinez@Welch-Wilson.Com,679.80,electronics,2024-05-16